TutorialPages = {
    0: ("Create an Account", "An administrator can manage (add/modify/remove) user accounts by going to \"Users -> Manage Users\". Only an administrator can make these changes once an administrative profile is configured on this system."),
    1: ("Welcome!", "Log in using your credentials to begin."),
    2: ("Forgot Password?", "See an administrator. They can manage your account and set a new password for you."),
    3: ("Perform a Measurement", "These tutorials will provide step-by-step directions on how to perform a measurement run."),
    3.1: ("Step 1. Temperature Control", "(Optional) Click \"Temp Control\" and set the desired target temperature. Wait for the device to cycle the temperature to the setpoint, which will take a few minutes. Once the target temperature is reached, the device will indicate \"Ready\"."),
    3.2: ("Step 2. Initialize Sensor", "Insert an unused quartz sensor into the device. Press \"Initialize\" with sensor exposed to ambient air environment (no sample yet)."),
    3.3: ("Step 3. Start Measurement", "Once initialized, the measurement may begin. Press \"Start\" to begin the measurement process. <b>NOTE: Wait to apply the drop</b> to the sensor until prompted to do so by the software, after hitting \"Start\"."),
    3.4: ("Step 4. Apply Drop to Sensor", "Apply the drop to the inlet of the sensor and watch on the software plots as the sensor fills with the sample. Wait for exit."),
    3.5: ("Step 5. Stop Measurement", "Once the sample has exited the sensor (typically characterized by a suddent shift in frequencies after the 3rd channel fill, or a stabilization of the signal with no changes), press \"Stop\" to finish data capture for this measurement."),
    3.6: ("Step 6. Enter Run Info", "Upon stopping the run, you will be prompted to enter the \"Run Info\" for this sample. Enter the information and adjust parameters as desired, which will be used during the Analyze phase later on. You can modify this later prior to Analyze, if need be."),
    4: ("Next Steps...", "Either repeat these steps with another sensor and sample, or proceed to \"Analyze\" mode to complete analysis for the measured sample(s)."),
    5: ("Analyze a Dataset", "These tutorials will provide step-by-step directions on how to perform the analysis of a run."),
    5.1: ("Step 1. Load a Run", "Select a run from the dropdown menu (by default: most recent runs shown first) and click \"Load\" to begin the analysis process."),
    5.2: ("Step 2. Review Run Info", "(Optional) Click \"Run Info\" after loading a run to see the parameters entered at capture time. You can modify these parameters here, if desired."),
    5.3: ("Step 3. Modify Points", "Click \"Modify\" to review the point selection, and to fine-tune the auto-calculated points to be used for the Analyze process."),
    5.4: ("Step 4. Analyze Data", "Once points are confirmed, click \"Analyze\" to execute the Analyze process and calculate the final results for this dataset. You can modify points, and repeat \"Analyze\" again, as desired."),
    6: ("View Previous Results", "You can view the saved results from previously analyzed data by loading the prior run, and skipping straight to clicking \"Analyze\". The prior results using previously selected points will be displayed after re-performing the analysis."),
    7: ("Modify Point Selection", "These tutorials will guide you through fine-tuning the point selections used for the analyze process."),
    7.1: ("Select Precise Fill Point 1", "The first point in the dataset corresponds to where the frequencies begin to deviate from the baseline, which is when the drop was first applied to the inlet."),
    7.2: ("Select Precise Fill Point 2", "The second point in the dataset corresponds to the end of the initial fill region, which is where the steep slope of the initial fill region slows down, and continues towards the 1st channel fill point."),
    7.3: ("Select Precise Fill Point 3", "The third point in the dataset corresponds to the post-fill point, after the signal has stabilized from the sudden spikes of the initial fill region. This point is often just a few samples after Point 2."),
    7.4: ("Select Precise Fill Point 4", "The fourth point in the dataset corresponds to the 1st channel fill point, which corresponds to the first inflecion point of the three channnel fill regions. See Note below."),
    7.5: ("Select Precise Fill Point 5", "The fifth point in the dataset corresponds to the 2nd channel fill point, which corresponds to the 2nd inflecion point of the three channnel fill regions. See Note below."),
    7.6: ("Select Precise Fill Point 6", "The sixth point in the dataset corresponds to the 3rd channel fill point, which corresponds to the 3rd inflecion point of the three channnel fill regions, or where the frequencies start to drift quickly away from the stable data region. See Note below."),
    7.7: ("Note: Precise Point Placement", "If a blip is present in the region of the point, select a point just before the blip; otherwise, select a point close to the inflection point when no obvious blip is present in the data.")
    #: ("Title", "Description Text"),
}
