from src.models.ingredient import Protein, Buffer, Salt, Stabilizer, Surfactant
from src.models.formulation import Formulation, ViscosityProfile
if __name__ == "__main__":
    protein = Protein(-1, 'PROTEIN', 100, 10, 1)
    buffer = Buffer(-1, 'BUFFER', 10)
    salt = Salt(-1, 'SALT')
    stabilizer = Stabilizer(-1, 'STABILIZER')
    surfactant = Surfactant(-1, 'SURFACTANT')
    vp = ViscosityProfile([100, 1000, 10000, 100000, 15000000],
                          [10, 10, 10, 10, 9], 'mg/ml')
    formulation = Formulation()
    formulation.set_buffer(buffer, 10, 'mg/ml')
    formulation.set_salt(salt, 100, 'mg/ml')
    formulation.set_stabilizer(stabilizer, 1, 'M')
    formulation.set_surfactant(surfactant, 0.1, "%w")
    formulation.set_protein(protein, 100, 'mg/ml')
    formulation.set_temperature(25)
    formulation.set_viscosity_profile(vp)
    formulation2 = Formulation()
    formulation2.set_buffer(buffer, 10, 'mg/ml')
    formulation2.set_salt(salt, 100, 'mg/ml')
    formulation2.set_stabilizer(stabilizer, 1, 'M')
    formulation2.set_surfactant(surfactant, 0.1, "%w")
    formulation2.set_protein(protein, 100, 'mg/ml')
    formulation2.set_temperature(25)
    formulation2.set_viscosity_profile(vp)
    print(formulation == formulation2)
    print(formulation.to_dict())
    print(formulation2.to_dict())
