name: "QModel Tuning Issue"
description: "Track issues related to QModel Tuning runs."
title: "[QModel] <Brief summary of issue>"
labels: ["qmodel", "tuning"]
assignees:
  - <PaulMacNichol>

body:
  - type: input
    id: date-created
    attributes:
      label: "Date Created"
      description: "Date the issue was reported."
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of the issue."
      options:
        - "Open"
        - "In Progress"
        - "Closed"
      default: 0
    validations:
      required: true

  - type: input
    id: run-file
    attributes:
      label: "Run File (.zip)"
      description: "Attach or link the run file associated with this tuning."
      placeholder: "Drag file here or paste URL"
    validations:
      required: true

  - type: textarea
    id: data-issues
    attributes:
      label: "Issues with Data"
      description: "Describe specific issues identified with the data."
      placeholder: "Examples: Runtime anomalies"
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Additional Notes"
      description: "Additional context, follow-up actions, or other relevant details."
      placeholder: "Provide extra observations, screenshots, logs, or links here."
    validations:
      required: false
