"""
QATCH.ui.components.qatch_panel.py

Reusable content panel.

This module provides :class:`QATCHPanel`, a lightweight `QFrame` that renders
a static flat surface - the same fill/border recipe as the rest of the app's
flat control system (see :mod:`QATCH.ui.components.flat_paint`), so a panel
reads as the same kind of surface as a QATCHLineEdit or QATCHOptionCard
instead of a visually distinct "glass" family.

The panel renders an opaque fill so child widgets remain fully legible
regardless of the contents behind the panel. This makes it suitable for
dialogs, forms, grouped controls, and other persistent content containers.

The panel automatically responds to application theme changes through
:class:`ThemeManager` and supports an optional "danger" variant that swaps
the fill/border to the theme's error tokens while preserving the shared
rendering recipe.

Example:
    panel = QATCHPanel()
    layout = QtWidgets.QVBoxLayout(panel)

    warning_panel = QATCHPanel(danger=True)

Author(s):
    Paul MacNichol (paul.macnichol@qatchtech.com)

Date:
    2026-08-05
"""

from __future__ import annotations

from PyQt5 import QtCore, QtGui, QtWidgets

from QATCH.ui.components.flat_paint import paint_flat_surface
from QATCH.ui.styles.theme_manager import ThemeManager

_RADIUS = 10.0


class QATCHPanel(QtWidgets.QFrame):
    """Static flat content panel.

    This widget renders a themed flat surface using the shared painting
    pipeline while providing an opaque fill so child widgets are never
    visually blended with the background. It is intended for reusable content
    containers throughout the application.

    Attributes:
        _danger: Whether the panel uses the danger-tinted variant.
    """

    def __init__(self, parent: QtWidgets.QWidget | None = None, *, danger: bool = False) -> None:
        """Initializes the flat panel.

        Args:
            parent: Optional parent widget.
            danger: If `True`, the panel is tinted toward the theme's error
                color while retaining the standard appearance.
        """
        super().__init__(parent)
        self._danger = danger
        self.setAutoFillBackground(False)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_NoSystemBackground, True)
        ThemeManager.instance().themeChanged.connect(self._on_theme_changed)

    def _on_theme_changed(self, _mode: str) -> None:
        """Refreshes the panel after the application theme changes.

        Args:
            _mode: Name of the newly activated theme.
        """
        self.update()

    def paintEvent(self, event: QtGui.QPaintEvent) -> None:
        """Paints the flat panel.

        Retrieves the current theme tokens and delegates rendering to the
        shared `paint_flat_surface()` helper - the same fill/border/radius
        recipe every other flat control uses. The panel is rendered with an
        opaque fill to ensure child widgets remain visually isolated from
        the background.

        Args:
            event: Paint event generated by Qt.
        """
        tok = ThemeManager.instance().tokens()
        if self._danger:
            fill = QtGui.QColor(*tok["flat_error_weak"])
            border = QtGui.QColor(*tok["flat_error"])
        else:
            fill = QtGui.QColor(*tok["flat_surface"])
            border = QtGui.QColor(*tok["flat_border"])

        p = QtGui.QPainter(self)
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        paint_flat_surface(self, radius=_RADIUS, fill=fill, border=border, painter=p)
        p.end()
