"""
QATCH.ui.widgets.qatch_card.py

Ccard widget for the QATCH login interface.

This module provides :class:`QATCHCard`, a custom `QFrame` that renders a
live frosted effect by sampling the blurred backdrop maintained by a
:class:`LoginCentralWidget`. Unlike traditional translucent widgets that rely
on platform composition or semi-transparent backgrounds, this implementation
reconstructs the appearance entirely in software, ensuring consistent
visual results across platforms and Qt styles.

The card's rendering pipeline:

    1. Clips all painting to a rounded rectangle.
    2. Samples the corresponding region of the shared blurred backdrop.
    3. Falls back to a themed gradient when no backdrop is available.
    4. Applies configurable tint and shimmer overlays.
    5. Draws layered borders using theme-defined colors.
    6. Optionally renders an animated emphasis border used during UI
       transitions.

All visual styling is driven by :class:`ThemeManager`, allowing the widget to
adapt automatically to application theme changes while maintaining a consistent
appearance throughout the interface.

Author(s):
    Paul MacNichol (paul.macnichol@qatchtech.com)

Date:
    2026-08-05
"""

from PyQt5 import QtCore, QtGui, QtWidgets

from QATCH.ui.styles.theme_manager import ThemeManager
from QATCH.ui.widgets.login_central_widget import LoginCentralWidget


class QATCHCard(QtWidgets.QFrame):
    """Card that renders a live blurred backdrop.

    This widget implements the frosted-glass panels used throughout the login
    interface. Rather than drawing a static translucent background, it samples
    the blurred snapshot maintained by a :class:`LoginCentralWidget`, allowing
    the card to remain visually synchronized with animated background blur and
    dimming effects.

    During painting the widget:

    1. Clips rendering to a rounded rectangle.
    2. Samples the appropriate region of the shared blurred backdrop.
    3. Applies configurable glass tint and shimmer overlays.
    4. Draws multi-layer glass borders.
    5. Optionally renders an animated emphasis border.

    If no backdrop snapshot is available, a theme-defined fallback gradient is
    rendered instead.

    Attributes:
        _RADIUS: Corner radius, in pixels, used for all rounded geometry.
        _backdrop: Widget supplying blurred and unblurred background snapshots.
        _border_frac: Progress of the animated emphasis border in the range
            `[0.0, 1.0]`.
    """

    _RADIUS: float = 22.0

    def __init__(
        self,
        backdrop: LoginCentralWidget,
        parent: QtWidgets.QWidget | None = None,
    ) -> None:
        """Initializes the card.

        Stores the backdrop provider and configures the frame for fully custom
        painting by disabling Qt's default background rendering.

        Args:
            backdrop: Login widget that provides the blurred backdrop images.
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self._backdrop = backdrop
        self._border_frac: float = 0.0

        # Prevent the base class from painting opaque backgrounds
        self.setAutoFillBackground(False)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_NoSystemBackground, True)

    def set_border_frac(self, value: float) -> None:
        """Sets the animated emphasis border progress.

        The supplied value is clamped to the range `[0.0, 1.0]` before
        scheduling a repaint.

        Args:
            value: Border animation progress, where `0.0` hides the emphasis
                border and `1.0` displays it at full intensity.
        """
        self._border_frac = max(0.0, min(1.0, value))
        self.update()

    def paintEvent(self, event: QtGui.QPaintEvent) -> None:
        """Paints the entire card.

        The entire appearance is rendered manually instead of relying on Qt
        stylesheets so that the translucent effect remains intact.

        The rendering sequence is:

        1. Enable antialiasing and smooth pixmap rendering.
        2. Clip painting to a rounded rectangle.
        3. Draw the corresponding region of the shared blurred backdrop, or a
           fallback gradient if no backdrop exists.
        4. Apply theme-defined tint and shimmer overlays.
        5. Draw the outer rim and inner inset borders.
        6. Render the optional animated emphasis border.

        Args:
            event: Paint event generated by Qt.
        """
        p = QtGui.QPainter(self)
        p.setRenderHints(QtGui.QPainter.Antialiasing | QtGui.QPainter.SmoothPixmapTransform)

        rect_f = QtCore.QRectF(self.rect())
        clip = QtGui.QPainterPath()
        clip.addRoundedRect(rect_f, self._RADIUS, self._RADIUS)
        p.setClipPath(clip)
        blurred = getattr(self._backdrop, "_blurred", None)
        sharp = getattr(self._backdrop, "_raw_snapshot", None)
        if (blurred is not None and not blurred.isNull()) or (
            sharp is not None and not sharp.isNull()
        ):
            origin = self.mapTo(self._backdrop, QtCore.QPoint(0, 0))
            p.save()
            p.translate(-origin.x(), -origin.y())
            # Mirror the backdrop's blur/dim progress so the card's sampled
            # slice matches the area around it exactly during transitions.
            blur_frac = getattr(self._backdrop, "_blur_frac", 0.0)
            dim_frac = getattr(self._backdrop, "_dim_frac", 0.0)
            LoginCentralWidget._compose_backdrop(
                p,
                self._backdrop.rect(),
                sharp,
                blurred,
                blur_frac,
                dim_frac,
                ThemeManager.instance().tokens(),
            )
            p.restore()
        else:
            tokens = ThemeManager.instance().tokens()
            grad = QtGui.QLinearGradient(0, 0, 0, self.height())
            grad.setColorAt(0.0, QtGui.QColor(*tokens["backdrop_fallback_start"]))
            grad.setColorAt(1.0, QtGui.QColor(*tokens["backdrop_fallback_end"]))
            p.fillRect(self.rect(), QtGui.QBrush(grad))

        # Tint and shimmer effects.
        tokens = ThemeManager.instance().tokens()
        p.fillRect(self.rect(), QtGui.QColor(*tokens["plot_glass_shimmer_top"]))
        p.fillRect(self.rect(), QtGui.QColor(*tokens["plot_glass_overlay"]))
        shimmer = QtGui.QLinearGradient(0, 0, 0, 80)
        shimmer.setColorAt(0.0, QtGui.QColor(*tokens["plot_glass_shimmer_mid"]))
        shimmer.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        p.fillRect(self.rect(), QtGui.QBrush(shimmer))
        p.setClipping(False)
        p.setBrush(QtCore.Qt.BrushStyle.NoBrush)
        p.setPen(QtGui.QPen(QtGui.QColor(*tokens["plot_glass_rim"]), 1.0))
        p.drawRoundedRect(rect_f.adjusted(0.5, 0.5, -0.5, -0.5), self._RADIUS, self._RADIUS)
        p.setPen(QtGui.QPen(QtGui.QColor(*tokens["plot_glass_inset"]), 1.0))
        p.drawRoundedRect(
            rect_f.adjusted(1.5, 1.5, -1.5, -1.5),
            self._RADIUS - 1.5,
            self._RADIUS - 1.5,
        )

        # Emphasis border
        if self._border_frac > 0.0:
            rim = tokens["plot_glass_rim"]
            p.setPen(
                QtGui.QPen(
                    QtGui.QColor(rim[0], rim[1], rim[2], int(210 * self._border_frac)),
                    1.0,
                )
            )
            p.drawRoundedRect(rect_f.adjusted(0.5, 0.5, -0.5, -0.5), self._RADIUS, self._RADIUS)

        p.end()
