"""
QATCH.ui.components.qatch_panel.py

Reusable content panel.

This module provides :class:`QATCHPanel`, a lightweight ``QFrame`` that renders
a static frosted surface.

Unlike translucent overlay widgets, the panel renders an opaque base so
child widgets remain fully legible regardless of the contents behind the panel.
This makes it suitable for dialogs, forms, grouped controls, and other
persistent content containers.

The panel automatically responds to application theme changes through
:class:`ThemeManager` and supports an optional "danger" variant that blends the
standard tint with the theme's danger color while preserving the shared
rendering recipe.

Example:
    panel = QATCHPanel()
    layout = QtWidgets.QVBoxLayout(panel)

    warning_panel = QATCHPanel(danger=True)

Author(s):
    Paul MacNichol (paul.macnichol@qatchtech.com)

Date:
    2026-08-05
"""

from __future__ import annotations

from PyQt5 import QtCore, QtGui, QtWidgets

from QATCH.ui.components.glass_paint import paint_glass_surface
from QATCH.ui.styles.theme_manager import ThemeManager

_RADIUS = 12.0


class QATCHPanel(QtWidgets.QFrame):
    """Static frosted-glass content panel.

    This widget renders a themed glass surface using the shared painting
    pipeline while providing an opaque base layer so child widgets are never
    visually blended with the background. It is intended for reusable content
    containers throughout the application.

    Attributes:
        _danger: Whether the panel uses the danger-tinted glass variant.
    """

    def __init__(self, parent: QtWidgets.QWidget | None = None, *, danger: bool = False) -> None:
        """Initializes the glass panel.

        Args:
            parent: Optional parent widget.
            danger: If ``True``, the panel is tinted toward the theme's danger
                color while retaining the standard appearance.
        """
        super().__init__(parent)
        self._danger = danger
        self.setAutoFillBackground(False)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_NoSystemBackground, True)
        ThemeManager.instance().themeChanged.connect(self._on_theme_changed)

    def _on_theme_changed(self, _mode: str) -> None:
        """Refreshes the panel after the application theme changes.

        Args:
            _mode: Name of the newly activated theme.
        """
        self.update()

    def paintEvent(self, event: QtGui.QPaintEvent) -> None:
        """Paints the frosted panel.

        Retrieves the current theme tokens, optionally blends the base color
        toward the theme's danger color, and delegates rendering to the shared
        ``paint_glass_surface()`` helper. The panel is rendered with an opaque base
        fill to ensure child widgets remain visually isolated from the background.

        Args:
            event: Paint event generated by Qt.
        """
        tokens = ThemeManager.instance().tokens()

        if self._danger:
            base = tokens["plot_glass_base"]
            danger = tokens["danger"]
            tokens = dict(tokens)
            tokens["plot_glass_base"] = (
                (base[0] + danger[0]) // 2,
                (base[1] + danger[1]) // 2,
                (base[2] + danger[2]) // 2,
                base[3],
            )

        p = QtGui.QPainter(self)
        p.setRenderHints(QtGui.QPainter.Antialiasing | QtGui.QPainter.SmoothPixmapTransform)
        paint_glass_surface(
            self,
            radius=_RADIUS,
            tokens=tokens,
            painter=p,
            shimmer_height=40.0,
            draw_vignette=False,
            opaque_base=True,
        )
        p.end()
