name: "nightly"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 1-5' # runs daily at 00:00 UTC, Mon - Fri only

jobs:
  nightly_build:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: windows-latest
    name: Nightly build nanovisQ
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: main
      - run: git pull
        
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install --upgrade pip
      - run: pip install -r main/requirements.txt
          
      - name: Run nightly build script
        run: python main/tagger.py --nightly

  check_date:
    runs-on: windows-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: Print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
