name: "nightly"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '59 23 * * 1-5' # runs daily at 23:59 UTC, Mon - Fri only

jobs:
  nightly_build:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: windows-latest
    name: Nightly build nanovisQ
    outputs:
      artifact_name: ${{ steps.tagger.outputs.artifact_name }}
      tag_name: ${{ steps.tagger.outputs.tag_name }}
    steps:
      - name: Checkout repo to 'trunk'
        uses: actions/checkout@v4
        with:
          path: trunk
        
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip' # caching pip dependencies
      # - run: python -m pip install --upgrade pip # might as well
      # - run: python -m pip install -r trunk/requirements.txt
          
      - name: Run nightly build script (w/ outputs)
        id: tagger
        run: |
          python trunk/tagger.py --nightly
          echo "$env:GITHUB_OUTPUT"
          cat build_name.var
          cat build_date.var
          echo "build_name=$(cat build_name.var)" >> "$env:GITHUB_OUTPUT"
          echo "build_date=$(cat build_date.var)" >> "$env:GITHUB_OUTPUT"
          cat "$env:GITHUB_OUTPUT"
        # echo "artifact_name=$build_name" >> "$env:GITHUB_OUTPUT"
        # echo "tag_name=$build_name $build_date" >> "$env:GITHUB_OUTPUT"
        # echo "::set-output name=artifact_name::%build_name%"
        # echo "::set-output name=tag_name::%build_name% %build_date%"

      - name: Print build output values
        run: |
          echo Build Name: ${{ steps.tagger.outputs.build_name }}
          echo Build Date: ${{ steps.tagger.outputs.build_date }}
          echo Artifact Name: ${{ steps.tagger.outputs.build_name }}
          echo Tag Name: ${{ steps.tagger.outputs.build_name }} ${{ steps.tagger.outputs.build_date }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        env:
          build_name: ${{ steps.tagger.outputs.build_name }}
          build_date: ${{ steps.tagger.outputs.build_date }}
          artifact_name: ${{ env.build_name }}
          tag_name: ${{ env.build_name }} ${{ env.build_date }}
        with:
          name: ${{ env.artifact_name }}
          path: tags/nightly/${{ env.tag_name }}/dist/*.zip
          if-no-files-found: error
          retention-days: 7

  check_date:
    runs-on: windows-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: trunk
      - name: Print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          test -z $(git rev-list  --after="24 hours"  ${{ github.sha }})
          echo "should_run=false" >> "$env:GITHUB_OUTPUT"
